name: MagicBottle

main: vontus.magicbottle.Plugin
version: 1.1.0

author: Vontus

commands:
  magicbottle:
    description: 'Main plugin command'
    aliases: [mb, magicb, mbottle]

permissions:
  magicbottle.action.craft:
    description: 'Allows you to craft MagicBottles'
    default: true
  magicbottle.action.deposit:
    description: 'Allows you to deposit experience in MagicBottles'
    default: true
  magicbottle.action.withdraw:
    description: 'Allows you to withdraw experience from MagicBottles'
    default: true
  magicbottle.command.repair:
    description: 'Allows you to repair tools with bottled XP'
    default: true
  magicbottle.command.repair.auto:
    description: 'Allows you to repair tools automatically with bottled XP'
    default: true
  magicbottle.command.give:
    description: 'Admin command. Gives you or another player a number of bottles of a certain level'
  magicbottle.command.reload:
    description: 'Admin command. Reloads the plugin config'
  magicbottle.maxlevel.unlimited:
    description: 'Allows you to save up to 20,000 levels in a single MagicBottle'
    default: false