# --------------------- MagicBottle Configuration ---------------------

# Config:

general:
  # Enables sound and particle effects in the whole plugin
  effects:
    sound: true
    particles: true

  # Enables the ability to use a crafting grid to save or take all xp from MagicBottles
  # Disable this if you're having trouble with other crafting plugins
  crafting grid transfer xp: true

  # Makes the plugin use a custom invisible enchantment to make MagicBottles glow
  # Disabling this will cause all MagicBottles to have the Infinity enchantment
  # Disable this if MagicBottles stop working
  use custom enchantment: true

permission groups:
  # DON'T DELETE THIS GROUP
  # The default group will be applied when the user doesn't have any other group permission
  default:
    # Max level players in this group can save in a MagicBottle
    # This can't be more than 20,000 levels (that's 1,796,752,220 XP!)
    max level: 200
    repair:
      # Ability to repair equipment with XP saved in MagicBottles
      enabled: true
      # Ability to make MagicBottles repair equipment automatically
      auto: true
    costs:
      # Percentage of XP lost when depositing in a MagicBottle (should be from 0 to 49 max to get the best result)
      xp-percentage: 0
      # Money needed to create a new bottle. Vault is required for this to take effect.
      new bottle money: 0

  custom groups:
    # You need to grant people the permission 'magicbottle.group.<name>', being '<name>' in the list shown below
    # If a player is assigned two or more of these groups, the one with the greater priority will be applied
    #   For example, a VIP can have the permissions 'vip' and 'veteran', but only 'vip' will be applied
    # Make sure two groups don't have the same priority
    # You can modify, add or remove any of the following groups at will, just be careful with indentation (spaces only)
    veteran:
      priority: 1
      max level: 200
      repair:
        enabled: true
        auto: true

    vip:
      priority: 2
      max level: 200
      repair:
        enabled: true
        auto: true
      costs:
        xp-percentage: 0
        new bottle money: 0