# --------------------- MagicBottle Configuration ---------------------

# Config:

# Enables sound and particle effects in the whole plugin
effect:
  sound: true
  particles: true

recipe:
  # Enables the ability to fill or pour bottles by putting them in a crafting grid
  # You must restart your server after changing any of the recipes configurations
  deposit: true
  withdraw: true
  # Enables the ability to craft new MagicBottles
  # If you disable this, players won't be able to craft new bottles but existing ones will remain usable
  bottle:
    enabled: true
    # Defines the items needed to craft a new empty MagicBottle
    # These items need to be thrown inside a valid cauldron (filled with water and fire underneath)
    # Players need to right click with an empty vanilla bottle after throwing all the items
    # The order is irrelevant
    # You can see a complete list of possible item materials here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    ingredients:
      - material: BLAZE_POWDER
        amount: 2
      - material: GLOWSTONE_DUST
        amount: 2
      - material: ENDER_CHEST
        amount: 1
      - material: GOLD_BLOCK
        amount: 3

# Set the maximum level a player can save in a single MagicBottle
# TIP: Set this depending on how difficult you made the recipe
max level:
  # This max level will be applied when the player doesn't have any of the following permissions
  default: 200
  permissions:
    # Allow players to have bottles with more levels than the default option
    # To remove the limit entirely, give people 'magicbottle.maxlevel.unlimited'; still, the maximum level a bottle can hold is 20,000 (that's 1,796,752,220 XP!)
    # You need to grant people the permission 'magicbottle.maxlevel.<name>', being <name> in the list shown below
    # If a player has two or more of these permissions, the maximum value will be applied, including 'magicbottle.maxlevel.unlimited'
    #   For example, a Veteran user can have the permissions 'user' and 'veteran', but only 'veteran' will be applied
    # You can modify, add or remove any of the following limits at will
    user: 300
    veteran: 350
    vip: 400

repair:
  # Enable or disable the '/mb repair' command
  enabled: true
  # Enable or disable the '/mb repair auto' command
  auto: true

# Here you can configure what percentage of experience will be charged when transferring experience.
costs:
  deposit:
    # Integer from 0 to 100.
    # Values from 50 to 100 might take experience without saving any in the bottle.
    # I'd recommend using a value from 0 to 49.
    exp-percentage: 0
  craft new bottle:
    # Money needed to create a new bottle. Vault is required for this to take effect.
    money: 0
    # Whether to change the bottle lore when it is about to be crafted to tell the player how much it will cost.
    # Enable this if you set a cost. The custom lore is in messages.yml
    # Restart the server after changing this.
    change lore: false
