name: MagicBottle

main: vontus.magicbottle.Plugin
version: 1.4.3

author: Vontus

commands:
  magicbottle:
    description: 'Main plugin command'
    aliases: [mb, magicb, mbottle]

permissions:
  magicbottle.action.craft:
    description: 'Allows a player to craft MagicBottles'
    default: true
  magicbottle.action.deposit:
    description: 'Allows a player to save experience in MagicBottles'
    default: true
  magicbottle.action.withdraw:
    description: 'Allows a player to take experience from MagicBottles'
    default: true
  magicbottle.command.repair:
    description: 'Allows a player to repair tools using bottled XP'
    default: true
  magicbottle.command.repair.auto:
    description: 'Allows a player to repair tools automatically using bottled XP'
    default: true
  magicbottle.command.give:
    description: 'Admin command. Gives you or another player a number of bottles of a certain level'
  magicbottle.command.reload:
    description: 'Admin command. Reloads the plugin config'
  magicbottle.maxlevel.unlimited:
    description: 'Allows a player to save up to 20,000 levels in a single MagicBottle'
    default: false
  magicbottle.action.craft.cost.exempt:
    description: 'Exempts the player from paying the cost of crafting a new bottle'
    default: false
  magicbottle.action.deposit.cost.exempt:
    description: 'Exempts the player from paying the cost of saving experience into a bottle'
    default: false
